<a href="https://colab.research.google.com/github/tapasmeher10/Kaggle/blob/main/titanic_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import Libraries

In [27]:
import numpy as np
import pandas as pd
import tensorflow as tf

##Importing Dataset

In [28]:
dataset=pd.read_csv("train.csv")
testset=pd.read_csv("test.csv")

#**Preprocessing the Data**


##Nan value

In [29]:
dataset.columns[dataset.isna().any()]

Index(['Age', 'Embarked'], dtype='object')

In [30]:
testset.columns[testset.isna().any()]

Index(['Age', 'Fare'], dtype='object')

In [31]:
dataset.Age=dataset.Age.fillna(dataset.Age.mean())

In [32]:
dataset.dropna(inplace = True)

In [33]:
dataset.columns[dataset.isna().any()]

Index([], dtype='object')

In [34]:
testset.Age=testset.Age.fillna(testset.Age.mean())

In [35]:
testset.Fare=testset.Fare.fillna(testset.Fare.mean())

##split into x and y

In [36]:
X=dataset.iloc[: ,3:-1].values
y=dataset.iloc[:,-1].values

In [37]:
xt=testset.iloc[:,2:].values

In [38]:
print(xt)

[[3 'male' 34.5 ... 0 'Q' 7.8292]
 [3 'female' 47.0 ... 0 'S' 7.0]
 [2 'male' 62.0 ... 0 'Q' 9.6875]
 ...
 [3 'male' 38.5 ... 0 'S' 7.25]
 [3 'male' 30.272590361445783 ... 0 'S' 8.05]
 [3 'male' 30.272590361445783 ... 1 'C' 22.3583]]


##encoding categorical data

In [39]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,1]=le.fit_transform(X[:,1])
xt[:,1]=le.fit_transform(xt[:,1])
print(X)

[[3 1 22.0 ... 0 'S' 7.25]
 [1 0 38.0 ... 0 'C' 71.2833]
 [3 0 26.0 ... 0 'S' 7.925]
 ...
 [3 0 29.69911764705882 ... 2 'S' 23.45]
 [1 1 26.0 ... 0 'C' 30.0]
 [3 1 32.0 ... 0 'Q' 7.75]]


##**one hot encoding**


In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5])],remainder='passthrough')
tct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
xt=np.array(tct.fit_transform(xt))

In [41]:
print(X)

[[0.0 0.0 1.0 ... 1 0 7.25]
 [1.0 0.0 0.0 ... 1 0 71.2833]
 [0.0 0.0 1.0 ... 0 0 7.925]
 ...
 [0.0 0.0 1.0 ... 1 2 23.45]
 [1.0 0.0 0.0 ... 0 0 30.0]
 [0.0 1.0 0.0 ... 0 0 7.75]]


##Feature scalling

In [42]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X) 

In [43]:
from sklearn.preprocessing import StandardScaler
sc1=StandardScaler()
xt=sc1.fit_transform(xt) 

##ANN modeling

In [44]:
ann=tf.keras.models.Sequential()

In [45]:
ann.add(tf.keras.layers.Dense(units=4,activation='relu'))

In [47]:
ann.add(tf.keras.layers.Dense(units=4,activation='relu'))

In [48]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

##Training the ANN

In [49]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [50]:
ann.fit(X,y,batch_size=32,epochs=1000)

Epoch 1/1000
28/28 [==============================] - 1s 1ms/step - loss: 0.7157 - accuracy: 0.6175
Epoch 2/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.7023 - accuracy: 0.6175
Epoch 3/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.6923 - accuracy: 0.6175
Epoch 4/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.6848 - accuracy: 0.6175
Epoch 5/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.6754 - accuracy: 0.6175
Epoch 6/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.6484 - accuracy: 0.6175
Epoch 7/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.6185 - accuracy: 0.6175
Epoch 8/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.6020 - accuracy: 0.6175
Epoch 9/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.5910 - accuracy: 0.6175
Epoch 10/1000
28/28 [==============================] - 0s 1ms/step - loss: 0.5826 - accuracy: 0.6175

##predict xtest

In [51]:

y_pred=ann.predict(xt)
y_pred=(y_pred>0.5)

In [52]:
from sklearn.preprocessing import LabelEncoder
ley=LabelEncoder()
y_pred=ley.fit_transform(y_pred)
pred1 = pd.DataFrame(y_pred, columns=['PassengerId']).to_csv('data11.csv')

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
